services:
  - type: web
    name: backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromSecret: database_url
      - key: ADMIN_TOKEN
        fromSecret: admin_token
